// react-todo/src/todo-list/todo-entries/TodoEntries.js
import React from 'react';
import './TodoEntries.css';
import PropTypes from 'prop-types';

function TodoEntries(props) {
  const { entries } = props;
  const list = entries.map(entry => <p>{entry}</p>);
  return (
    <div className="todos-entries">
      <p className="todo-entries-title">For today</p>
      {list}
    </div>
  );
}

TodoEntries.propTypes = {
  entries: PropTypes.arrayOf(PropTypes.string).isRequired
};

export default TodoEntries;

// angular-todo/src/app/todo-list/todo-entries/todo-entries.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-todo-entries',
  templateUrl: './todo-entries.component.html',
  styleUrls: ['./todo-entries.component.css']
})
export class TodoEntriesComponent {
  @Input()
  entries: string[] = [];
}

<div className="todos-entries">
  <p className="todo-entries-title">For today</p>
  <p *ngFor="let entry of entries">{{ entry }}</p>
</div>
