// angular-todo/src/app/posts-list/post/post.component.ts
import { Component, Input } from '@angular/core';
import { Post } from '../posts-service/posts.service';

@Component({
  selector: 'app-post',
  templateUrl: './post.component.html',
  styleUrls: ['./post.component.css']
})
export class PostComponent {
  @Input() post: Post;
}

<div>
  <span>{{ post.title }}</span>
  <span>{{ post.score }}</span>
</div>

// react-todo/src/posts-list/post/Post.js
import React from 'react';
import './Post.css';

function Post(props) {
  const { title, score } = props.post;
  return (
    <div className="post-wrapper">
      <span className="post-title">{title}</span>
      <span className="post-score">{'Score: ' + score}</span>
    </div>
  );
}

export default Post;
